# Generated by Django 5.2.14 on 2026-06-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status',
            field=models.CharField(choices=[('aguardando_peca', 'Aguardando peça'), ('em_andamento', 'Em andamento'), ('servico_concluido', 'Serviço concluído')], default='aguardando_peca', max_length=20),
        ),
    ]
