# Generated by Django 5.2.14 on 2026-06-10 10:57

from django.db import migrations


def migrar_status_servico(apps, schema_editor):
    Servico = apps.get_model('servico', 'Servico')
    Servico.objects.filter(status='por_fazer').update(status='aguardando_peca')
    Servico.objects.filter(status='feito').update(status='servico_concluido')


def migrar_status_historico(apps, schema_editor):
    HistoricoStatus = apps.get_model('servico', 'HistoricoStatus')
    HistoricoStatus.objects.filter(status_novo='por_fazer').update(status_novo='aguardando_peca')
    HistoricoStatus.objects.filter(status_novo='feito').update(status_novo='servico_concluido')
    HistoricoStatus.objects.filter(status_anterior='por_fazer').update(status_anterior='aguardando_peca')
    HistoricoStatus.objects.filter(status_anterior='feito').update(status_anterior='servico_concluido')


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_atualiza_status'),
    ]

    operations = [
        migrations.RunPython(migrar_status_servico, migrations.RunPython.noop),
        migrations.RunPython(migrar_status_historico, migrations.RunPython.noop),
    ]
