# Generated by Django 5.2.14 on 2026-06-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_migra_dados_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🛠️', max_length=10)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Serviço oferecido',
                'verbose_name_plural': 'Serviços oferecidos',
                'ordering': ['ordem'],
            },
        ),
    ]
