# Generated by Django 5.2.14 on 2026-06-10 13:56

from django.db import migrations


def atualizar_status_pagamento(apps, schema_editor):
    Servico = apps.get_model('servico', 'Servico')
    for s in Servico.objects.all():
        if s.preco is not None and s.valor_pago >= s.preco:
            s.status_pagamento = 'pago'
        elif s.valor_pago > 0:
            s.status_pagamento = 'parcial'
        else:
            s.status_pagamento = 'pendente'
        s.save(update_fields=['status_pagamento'])


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_servico_preco_servico_status_pagamento_and_more'),
    ]

    operations = [
        migrations.RunPython(atualizar_status_pagamento, migrations.RunPython.noop),
    ]
