# Generated by Django 5.2.14 on 2026-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_migra_status_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
