# Generated by Django 5.2.14 on 2026-06-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0007_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='previsao_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de entrega'),
        ),
    ]
